{% set name = "pyproject-parser" %}
{% set version = "0.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyproject-parser-{{ version }}.tar.gz
  sha256: 2b3a73e99f1ad6c6416e8777f4a34e98986899191880f32f481a024d5c9fb43b

build:
  entry_points:
    - pyproject-parser=pyproject_parser.__main__:main
    - check-pyproject=pyproject_parser.__main__:check
    - pyproject-fmt=pyproject_parser.__main__:reformat
    - pyproject-info=pyproject_parser.__main__:info
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - apeye-core >=1.0.0
    - attrs >=20.3.0
    - click >=7.1.2
    - consolekit >=1.4.1
    - dom-toml >=0.4.0
    - domdf-python-tools >=2.8.0
    - natsort >=7.1.1
    - packaging >=20.9
    - python >=3.6
    - shippinglabel >=1.0.0
    - toml >=0.10.2
    - typing-extensions >=3.7.4.3
  run_constrained:
    - sdjson >=0.3.1

test:
  imports:
    - pyproject_parser
  commands:
    - pip check
    - pyproject-parser --help
    - check-pyproject --help
    - pyproject-fmt --help
  requires:
    - pip

about:
  home: https://github.com/repo-helper/pyproject-parser
  summary: Parser for 'pyproject.toml'
  license: MIT
  license_file: LICENSE
  doc_url: https://pyproject-parser.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - domdfcoding
